#!/usr/bin/env python3
"""Port Anime4K mpv HOOK GLSL (MIT, bloc97) to Metal compute kernels."""

from __future__ import annotations

import re
import sys
from pathlib import Path


HEADER = """// Generated from bloc97/Anime4K GLSL (MIT). Do not edit by hand.
// Regenerated by scripts/glsl_hooks_to_metal.py

#include <metal_stdlib>
using namespace metal;

constexpr sampler a4k_samp(coord::normalized, address::clamp_to_edge, filter::linear);

inline float4 sample_uv(texture2d<float> tex, float2 uv) {
    return tex.sample(a4k_samp, uv);
}

inline float4 sample_off(texture2d<float> tex, uint2 gid, uint2 dest, float2 off) {
    float2 uv = (float2(gid) + 0.5) / float2(dest) + off / float2(tex.get_width(), tex.get_height());
    return tex.sample(a4k_samp, uv);
}

inline float get_luma(float4 rgba) {
    return dot(float4(0.299, 0.587, 0.114, 0.0), rgba);
}

"""


def split_hooks(text: str) -> list[str]:
    parts = re.split(r"(?=//!DESC )", text)
    return [p for p in parts if "//!DESC" in p]


def meta(block: str) -> dict:
    def one(key: str) -> str | None:
        m = re.search(rf"//!{key} (.+)", block)
        return m.group(1).strip() if m else None

    binds = re.findall(r"//!BIND (.+)", block)
    width = one("WIDTH") or ""
    height = one("HEIGHT") or ""
    return {
        "desc": one("DESC") or "pass",
        "hook": one("HOOK") or "MAIN",
        "binds": binds,
        "save": one("SAVE"),
        "double": "2 *" in width or "2 *" in height,
        "components": int(one("COMPONENTS") or "4"),
    }


def extract_defines(block: str) -> list[tuple[str, str, str]]:
    found = re.findall(r"#define\s+(\w+)(\(.*?\))?\s+(.*)", block)
    cleaned = []
    for name, args, expr in found:
        expr = expr.split("//", 1)[0].strip()
        cleaned.append((name, args, expr))
    return cleaned


def extract_hook_body(block: str) -> str:
    m = re.search(r"vec4 hook\(\)\s*\{", block)
    if not m:
        raise SystemExit("no hook() in block")
    start = m.end()
    depth = 1
    i = start
    while i < len(block) and depth:
        if block[i] == "{":
            depth += 1
        elif block[i] == "}":
            depth -= 1
        i += 1
    return block[start : i - 1]


def replace_mat4(src: str) -> str:
    out = []
    i = 0
    while True:
        j = src.find("mat4(", i)
        if j < 0:
            out.append(src[i:])
            break
        out.append(src[i:j])
        k = j + 5
        depth = 1
        p = k
        while p < len(src) and depth:
            if src[p] == "(":
                depth += 1
            elif src[p] == ")":
                depth -= 1
            p += 1
        inner = src[k : p - 1]
        nums = [n.strip() for n in inner.split(",") if n.strip()]
        if len(nums) != 16:
            raise SystemExit(f"mat4 expected 16 floats, got {len(nums)}: {inner[:80]}")
        cols = [
            f"float4({nums[0]}, {nums[1]}, {nums[2]}, {nums[3]})",
            f"float4({nums[4]}, {nums[5]}, {nums[6]}, {nums[7]})",
            f"float4({nums[8]}, {nums[9]}, {nums[10]}, {nums[11]})",
            f"float4({nums[12]}, {nums[13]}, {nums[14]}, {nums[15]})",
        ]
        out.append("float4x4(" + ", ".join(cols) + ")")
        i = p
    return "".join(out)


def glsl_to_metal(body: str, binds: list[str]) -> str:
    body = replace_mat4(body)
    body = body.replace("ivec2 ", "int2 ")
    body = body.replace("ivec2(", "int2(")
    body = body.replace("vec4 ", "float4 ")
    body = body.replace("vec3 ", "float3 ")
    body = body.replace("vec2 ", "float2 ")
    body = body.replace("vec4(", "float4(")
    body = body.replace("vec3(", "float3(")
    body = body.replace("vec2(", "float2(")
    body = re.sub(r"\bfloat\s+", "float ", body)

    def tex_off(m: re.Match) -> str:
        return f"sample_off({m.group(1)}, gid, dest, {m.group(2)})"

    body = re.sub(r"(\w+)_texOff\((.*?)\)", tex_off, body)

    def tex_pos(m: re.Match) -> str:
        name = m.group(1)
        return f"sample_uv({name}, uv)"

    body = re.sub(r"(\w+)_tex\(\s*\1_pos\s*\)", tex_pos, body)
    body = re.sub(
        r"(\w+)_tex\((.*?)\)",
        lambda m: f"sample_uv({m.group(1)}, {m.group(2)})",
        body,
    )
    body = re.sub(r"(\w+)_pos", "uv", body)
    body = re.sub(r"(\w+)_size", r"float2(\1.get_width(), \1.get_height())", body)
    body = re.sub(r"(\w+)_pt", r"(float2(1.0) / float2(\1.get_width(), \1.get_height()))", body)

    body = re.sub(
        r"(sample_uv\(\w+, uv\)) - \(([^;]+)\);",
        r"\1 - float4(\2);",
        body,
    )
    return body


def kernel_name(desc: str, index: int) -> str:
    slug = re.sub(r"[^A-Za-z0-9]+", "_", desc).strip("_")
    return f"a4k_{index:02d}_{slug[:48]}"


def emit_kernel(index: int, block: str) -> tuple[str, dict]:
    info = meta(block)
    binds = []
    for name in info["binds"]:
        if name == "HOOKED" and "MAIN" in binds:
            continue
        binds.append(name)
    if "HOOKED" in binds:
        # HOOKED is an alias of MAIN for these files unless MAIN is absent.
        if "MAIN" not in binds:
            binds = ["MAIN" if b == "HOOKED" else b for b in binds]
        else:
            binds = [b for b in binds if b != "HOOKED"]

    defines = extract_defines(block)
    body = extract_hook_body(block)
    for name, args, expr in defines:
        expr = expr.strip()
        if args:
            # function-like: go_0(x_off, y_off)
            params = args.strip("()")
            body = re.sub(
                rf"\b{name}\(([^)]*)\)",
                lambda m, e=expr, p=params: expand_fn(e, p, m.group(1)),
                body,
            )
        else:
            body = re.sub(rf"\b{name}\b", f"({expr})", body)

    # After expanding macros, HOOKED_* still present in clamp last pass
    if "HOOKED" in body and "MAIN" in binds:
        body = body.replace("HOOKED", "MAIN")

    metal_body = glsl_to_metal(body, binds)
    metal_body = re.sub(r"\breturn\s+", "float4 r = ", metal_body)
    metal_body = "\n".join(
        ("    " + line if line.strip() else line) for line in metal_body.splitlines()
    )
    kname = kernel_name(info["desc"], index)

    args = []
    for i, name in enumerate(binds):
        args.append(f"    texture2d<float> {name} [[texture({i})]]")
    args.append(f"    texture2d<float, access::write> dst [[texture({len(binds)})]]")
    args.append("    uint2 gid [[thread_position_in_grid]]")
    arg_block = ",\n".join(args)
    src = (
        f"\n// {info['desc']}\n"
        f"kernel void {kname}(\n{arg_block}\n) {{\n"
        "    if (gid.x >= dst.get_width() || gid.y >= dst.get_height()) {\n"
        "        return;\n"
        "    }\n"
        "    uint2 dest = uint2(dst.get_width(), dst.get_height());\n"
        "    float2 uv = (float2(gid) + 0.5) / float2(dest);\n"
        f"{metal_body}\n"
        "    dst.write(r, gid);\n"
        "}\n"
    )
    info["binds"] = binds
    info["kernel"] = kname
    return src, info


def expand_fn(expr: str, params: str, args: str) -> str:
    names = [p.strip() for p in params.split(",")]
    values = [a.strip() for a in args.split(",")]
    out = expr
    for n, v in zip(names, values):
        out = re.sub(rf"\b{n}\b", v, out)
    return f"({out})"


def main() -> None:
    files = [Path(p) for p in sys.argv[1:-1]]
    dest = Path(sys.argv[-1])
    chunks = [HEADER]
    catalog = []
    index = 0
    for path in files:
        for block in split_hooks(path.read_text()):
            src, info = emit_kernel(index, block)
            chunks.append(src)
            catalog.append(info)
            index += 1
    dest.write_text("".join(chunks))
    print(f"wrote {dest} ({index} kernels)")
    for info in catalog:
        print(
            f"{info['kernel']}\tbinds={','.join(info['binds'])}\tsave={info['save']}\tdouble={info['double']}\tc={info['components']}"
        )


if __name__ == "__main__":
    main()
